module.exports =   [
    {
      weeknumber: 1,
      description: '',
      img: '',
      price: 44,
      sunday:'Long Run 12 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
      qty: 99
    },
    {
      weeknumber: 2,
      description: '45 Miles Prescribed',
      img: '',
      price: 45,
      sunday:'Long Run 14 Miles',
      monday: 'Day Off',
      tuesday: 'Reg Run 7 Miles',
      wednesday: 'Intervals 9 Miles',
      thursday: 'Reg Run 7 Miles',
      friday: 'Flex Day 6 Miles',
      saturday: 'AYF 8 Miles',
      qty: 1
    },
    {
      weeknumber:  3,
      description: '45 Miles Prescribed',
      img: '',
      price: 45,
      sunday:'Long Run 16 Miles',
      monday: 'Day Off',
      tuesday: 'Reg Run 7 Miles',
      wednesday: 'Intervals 9 Miles',
      thursday: 'Reg Run 8 Miles',
      friday: 'Flex Day 6 Miles',
      saturday: 'AYF 8 Miles',
      qty: 0
    },
    {weeknumber:  4,
    description: '45 Miles Prescribed',
    img: '',
    qty: 45,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    price: 1000000
  },
  {
    weeknumber: 5,
    description: '44 Miles Prescribed',
    img: '',
    price: 44,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    qty: 72
  },
  {
    weeknumber: 6,
    description: '49 Miles Prescribed',
    img: '',
    price: 49,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    qty: 0
  },
  {
    weeknumber: 7,
    description: '47 Miles Prescribed',
    img: '',
    price: 47,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    qty: 913462
  }, 
  {
    weeknumber:  8,
    description: '36 Miles Prescribed',
    img: '',
    price: 36,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    sat: 'AYF 8 Miles',
    qty: 14
  },
  {
    weeknumber: 9,
    description: '48 Miles Prescribed',
    img: '',
    price: 48,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    qty: 49
  },
  {
    weeknumber:  10,
    description: '34 Miles Prescribed',
    img: '',
    price: 34,
    sun:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Reg Run 7 Miles',
    wednesday: 'Intervals 9 Miles',
    thursday: 'Reg Run 8 Miles',
    friday: 'Flex Day 6 Miles',
    saturday: 'AYF 8 Miles',
    qty: 54
  },
  {
    weeknumber: 11,
    description: '25 Miles Prescribed',
    img: '',
    price: 25,
    sunday:'Long Run 16 Miles',
    monday: 'Day Off',
    tuesday: 'Regular Run 4 Miles',
    wednesday: 'Tempo 6 Miles',
    thursday: 'Flex Day 3 Miles',
    friday: 'Regular Run 4 Miles',
    saturday: 'Regular Run 4 Miles',
    qty: 54
  },
  {
    weeknumber: 12,
    description: '35 Miles Prescribed',
    img: '',
   price: 35,
   sunday:'As You Feel Run 3 Miles',
   monday: 'Day Off',
   tuesday: 'Day Off',
   wednesday: 'Tempo 3 Miles',
   thursday: 'As You Feel Run 3 Miles',
   friday: 'Flex Day 3 Miles',
   saturday: 'RACE DAY',
    qty: 54
  }
  ]
  